create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.versions (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.packages(id) on delete cascade,
  version text not null,
  release_date timestamptz,
  changelog text,
  created_at timestamptz not null default now(),
  unique (package_id, version)
);

create index if not exists idx_versions_package_id on public.versions(package_id);

alter table public.packages enable row level security;
alter table public.versions enable row level security;